from os import environ
from decouple import config


# Load environment variables
OPEN_AI_API_KEY = config("OPEN_AI_API_KEY")
CONFLUENCE_DOMAIN = config("CONFLUENCE_DOMAIN")
CONFLUENCE_USERNAME = config("CONFLUENCE_USERNAME")
CONFLUENCE_API_KEY = config("CONFLUENCE_API_KEY")
PERSIST_DIRECTORY = config("PERSIST_DIRECTORY")
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
LLM_OPENAI_MODEL = config("LLM_OPENAI_MODEL")
EMBEDDING_TEST_DATA = config("EMBEDDING_TEST_DATA")